/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectNameRouteRouteImport } from './routes/$projectName.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectNameIndexRouteImport } from './routes/$projectName.index'
import { Route as ProjectNameNewRouteImport } from './routes/$projectName.new'
import { Route as ProjectNameInvoiceIdRouteImport } from './routes/$projectName.$invoiceId'

const ProjectNameRouteRoute = ProjectNameRouteRouteImport.update({
  id: '/$projectName',
  path: '/$projectName',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectNameIndexRoute = ProjectNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectNameRouteRoute,
} as any)
const ProjectNameNewRoute = ProjectNameNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectNameRouteRoute,
} as any)
const ProjectNameInvoiceIdRoute = ProjectNameInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => ProjectNameRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$projectName': typeof ProjectNameRouteRouteWithChildren
  '/$projectName/$invoiceId': typeof ProjectNameInvoiceIdRoute
  '/$projectName/new': typeof ProjectNameNewRoute
  '/$projectName/': typeof ProjectNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$projectName/$invoiceId': typeof ProjectNameInvoiceIdRoute
  '/$projectName/new': typeof ProjectNameNewRoute
  '/$projectName': typeof ProjectNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$projectName': typeof ProjectNameRouteRouteWithChildren
  '/$projectName/$invoiceId': typeof ProjectNameInvoiceIdRoute
  '/$projectName/new': typeof ProjectNameNewRoute
  '/$projectName/': typeof ProjectNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$projectName'
    | '/$projectName/$invoiceId'
    | '/$projectName/new'
    | '/$projectName/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$projectName/$invoiceId' | '/$projectName/new' | '/$projectName'
  id:
    | '__root__'
    | '/'
    | '/$projectName'
    | '/$projectName/$invoiceId'
    | '/$projectName/new'
    | '/$projectName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectNameRouteRoute: typeof ProjectNameRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$projectName': {
      id: '/$projectName'
      path: '/$projectName'
      fullPath: '/$projectName'
      preLoaderRoute: typeof ProjectNameRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$projectName/': {
      id: '/$projectName/'
      path: '/'
      fullPath: '/$projectName/'
      preLoaderRoute: typeof ProjectNameIndexRouteImport
      parentRoute: typeof ProjectNameRouteRoute
    }
    '/$projectName/new': {
      id: '/$projectName/new'
      path: '/new'
      fullPath: '/$projectName/new'
      preLoaderRoute: typeof ProjectNameNewRouteImport
      parentRoute: typeof ProjectNameRouteRoute
    }
    '/$projectName/$invoiceId': {
      id: '/$projectName/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/$projectName/$invoiceId'
      preLoaderRoute: typeof ProjectNameInvoiceIdRouteImport
      parentRoute: typeof ProjectNameRouteRoute
    }
  }
}

interface ProjectNameRouteRouteChildren {
  ProjectNameInvoiceIdRoute: typeof ProjectNameInvoiceIdRoute
  ProjectNameNewRoute: typeof ProjectNameNewRoute
  ProjectNameIndexRoute: typeof ProjectNameIndexRoute
}

const ProjectNameRouteRouteChildren: ProjectNameRouteRouteChildren = {
  ProjectNameInvoiceIdRoute: ProjectNameInvoiceIdRoute,
  ProjectNameNewRoute: ProjectNameNewRoute,
  ProjectNameIndexRoute: ProjectNameIndexRoute,
}

const ProjectNameRouteRouteWithChildren =
  ProjectNameRouteRoute._addFileChildren(ProjectNameRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectNameRouteRoute: ProjectNameRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
